#!/usr/bin/env bash

set -e

root=$(cd "$(dirname "$0")" && cd .. && pwd)

command='cat /var/log/envoy/access.log.json | alp json -r --sort=sum -m "/api/contestant/benchmark_jobs/[0-9]+,/api/admin/clarifications/[0-9]+,/api/admin/clarifications/[0-9]+"'

ssh -t isucon-server3 "$command"
